site_name: "Introduction to Computing"
site_author: "John Foley <johnf@middlebury.edu>"
site_description: "Public Course Website for CS145 F2020 at Middlebury College."
docs_dir: "src"
use_directory_urls: false
repo_url: "https://github.com/jjfiv/cs145-f2020"
repo_name: "Github"
edit_uri: "tree/master/src/"
theme: 
    name: "readthedocs"
    custom_dir: "customize"
markdown_extensions:
    - extra
    - md_in_html
    - sane_lists
    - tables
    - nl2br
    - mdx_math
# Reading: 📖
# Video: 📺
nav:
    - 'About': 'index.md'
    - 'syllabus.md'
    - 'colors_ref.md'
